apiVersion: v1
kind: Service
metadata:
  namespace: isddc
  name:
  labels:
    app: isddc-monasca
    chart: monasca-0.6.4
    component: platformui
    heritage: Tiller
    release: isddc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30314
      targetPort: 80
  selector:
    app: isddc-monasca
    component:
