log:
  init:
    level: DEBUG
    output: both
    handlers: [log/default.log, /var/log/mec_api.log]
    datefmt: '%d/%b/%y:%H:%M:%S %z'
    logfmt: '[%(asctime)s] [%(processName)s.%(threadName)s:%(levelname)s] %(message)s'
  logger:
    output: stream
    datefmt: '%Y-%m-%d %H:%M:%S'
    logfmt: '[%(asctime)s] [%(module)s.%(funcName)s line:%(lineno)d] [%(levelname)s] %(message)s'
  simple:
    datefmt: '%Y-%m-%d %H:%M:%S'
    logfmt: '[%(asctime)s] [%(levelname)s] %(message)s'


#mongo:
#  mon:
#    host: mongodb://10.121.112.110:30017/mon


#influx:
#  init:
#    username: root
#    password: root
#  mon:
#    host: 10.121.112.110
#    port: 30886
#    database: mon


#kafka:
#  metrics:
#    hosts: 10.121.12.120:31092


#mysql:
#  init:
#    charset: utf8
#    autocommit: false
#    use_unicode: null
#    read_timeout: null
#    write_timeout: null
#    connect_timeout: 1d
#    connect_check_cycle: 10m
#  gqylpy:
#    db:
#    host:
#    port:
#    user:
#    passwd:
#    charset: utf8


#aliyun:
#  init:
#    timeout: 15s
#    method: post
#    protocol_type: https
#    accept_format: json
#  send_sms:
#    name: SendSms
#    ak: LTAI4G4NyZNncAmN2vUc1Vep
#    secret: 89QhmlEA7PtRQVTeHiPSEc6h8Wfn3m
#    region_id: cn-hangzhou
#    domain: dysmsapi.aliyuncs.com
#    version: 2017-05-25
#    SignName: 歌琪怡玲萍云
#    TemplateCode: SMS_175571781
#    PhoneNumbers: 15911146374
#  send_mail:
#    name: SingleSendMail
#    ak: LTAI4G9oLHvrtHXwWC25L247
#    secret: 1jtboO1MMl3PUIZLeggL5aHclNxXAa
#    region_id: cn-hangzhou
#    domain: dm.aliyuncs.com
#    version: 2015-11-23
#    AddressType: 1
#    ReplyToAddress: true
#    AccountName: trigger@mail.gqylpy.com
#    ToAddress: 137326237@qq.com
#    FromAlias: Untitled


#dbpool:
#  init:
#    mincached: 0
#    maxcached: 1
#    maxshared: 0
#    maxconnections: 2
#    blocking: true
#    maxusage: null
#    setsession: null
#    ping: 1
#  db1:
#    creator: pymysql
#    db:
#    host:
#    port:
#    user:
#    passwd:
#    charset: utf8
#    connect_timeout: 1d
#    autocommit: false
#    use_unicode: null
#    read_timeout: null
#    write_timeout: null
